---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-docker
  pre_tasks:
    - name: create testuser group
      group:
        name: testuser
        state: present
    - name: Create Test User
      user:
        name: testuser
        group: testuser
        append: 'yes'
        state: present
        shell: /bin/bash
  vars:
    docker_users:
      - testuser
